name: base_project
description: Alo ninjavan

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  http: ^0.13.5
  g_json: ^4.1.0
  call_log: ^4.0.0
  permission_handler: ^10.2.0
  fast_contacts: ^1.1.1
  url_launcher: ^6.1.7
  record: ^4.4.3
  audioplayers: ^1.1.1
  flutter_local_notifications: ^13.0.0
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  intl: ^0.18.0
  dart_ping: ^8.0.0
  firebase_dynamic_links: ^5.0.11

  stringee_flutter_plugin:
    git:
      url: https://github.com/stringeecom/stringee_flutter_plugin.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - android/
    - android/app/
    - android/app/src/
    - android/app/src/main/
    - android/app/src/main/res/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/java/
    - android/app/src/main/java/io/
    - android/app/src/main/java/io/flutter/
    - android/app/src/main/java/io/flutter/plugins/
    - android/app/src/main/kotlin/
    - android/app/src/main/kotlin/com/
    - android/app/src/main/kotlin/com/ninjavan/
    - android/app/src/main/kotlin/com/ninjavan/app_mobile/
    - android/app/src/debug/
    - android/app/src/profile/
    - android/gradle/
    - android/gradle/wrapper/
    - android/.gradle/
    - android/.gradle/7.4/
    - android/.gradle/7.4/checksums/
    - android/.gradle/7.4/fileHashes/
    - android/.gradle/7.4/fileChanges/
    - android/.gradle/7.4/vcsMetadata/
    - android/.gradle/7.4/executionHistory/
    - android/.gradle/7.4/dependencies-accessors/
    - android/.gradle/vcs-1/
    - android/.gradle/buildOutputCleanup/
    - android/app/src/main/kotlin/com/ninjavan/alo_ninja/
    - android/app/src/main/kotlin/com/ninjavan/alo_ninja/app_mobile/

  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNext-Bold.ttf
        - asset: assets/fonts/AvenirNext-BoldItalic.ttf
        - asset: assets/fonts/AvenirNext-DemiBold.ttf
        - asset: assets/fonts/AvenirNext-DemiBoldItalic.ttf
        - asset: assets/fonts/AvenirNext-Heavy.ttf
        - asset: assets/fonts/AvenirNext-HeavyItalic.ttf
        - asset: assets/fonts/AvenirNext-Italic.ttf
        - asset: assets/fonts/AvenirNext-Medium.ttf
        - asset: assets/fonts/AvenirNext-MediumItalic.ttf
        - asset: assets/fonts/AvenirNext-Regular.ttf
        - asset: assets/fonts/AvenirNext-UltraLight.ttf
        - asset: assets/fonts/AvenirNext-UltraLightItalic.ttf
          style: normal
    - family: HomeBottomBarIcon
      fonts:
        - asset: assets/fonts/HomeBottomBarIcon.ttf

