name: base_project
description: Alo ninjavan

version: 1.0.0+13

environment:
  sdk: ">=2.18.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.4
  shared_preferences: ^2.0.15
  http: ^0.13.5
  g_json: ^4.1.0
  call_log: ^4.0.0
  permission_handler: ^10.2.0
  fast_contacts: ^1.1.1
  url_launcher: ^6.1.7
  audioplayers: ^1.1.1
  flutter_local_notifications: ^13.0.0
  syncfusion_flutter_datepicker: 20.4.44
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  intl: ^0.18.0
  flutter_phone_direct_caller: ^2.1.1
  connectivity_plus: ^3.0.3
  device_apps: ^2.2.0
  uni_links: ^0.5.1
  flutter_background_service: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^4.0.1
  app_settings: ^4.0.3
  firebase_crashlytics: ^3.4.8
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  webview_flutter: ^2.0.13
  floor: ^1.4.2
  mobile_number: ^2.1.1

  stringee_flutter_plugin:
    git:
      url: https://github.com/stringeecom/stringee_flutter_plugin.git
      ref: 1.2.8
  collection: ^1.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - lib/screens/contact_devices/

  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNext-Bold.ttf
        - asset: assets/fonts/AvenirNext-BoldItalic.ttf
        - asset: assets/fonts/AvenirNext-DemiBold.ttf
        - asset: assets/fonts/AvenirNext-DemiBoldItalic.ttf
        - asset: assets/fonts/AvenirNext-Heavy.ttf
        - asset: assets/fonts/AvenirNext-HeavyItalic.ttf
        - asset: assets/fonts/AvenirNext-Italic.ttf
        - asset: assets/fonts/AvenirNext-Medium.ttf
        - asset: assets/fonts/AvenirNext-MediumItalic.ttf
        - asset: assets/fonts/AvenirNext-Regular.ttf
        - asset: assets/fonts/AvenirNext-UltraLight.ttf
        - asset: assets/fonts/AvenirNext-UltraLightItalic.ttf
          style: normal
    - family: HomeBottomBarIcon
      fonts:
        - asset: assets/fonts/HomeBottomBarIcon.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: 'assets/images/image_app.png'